apiVersion: v1
kind: Service
metadata:
  name: {{ include "webappv3-helm.fullname" . }}
  labels:
    {{- include "webappv3-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    {{- include "webappv3-helm.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
